name: Deploy React App
# rebuild
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

18    - name: Install & Build
19      env:
20        REACT_APP_BACKEND_URL: https://gradient-showcase-18.preview.emergentagent.com 
          run: |
22          cd frontend
23          npm install --legacy-peer-deps
24          npm install ajv-keywords@3.5.2 ajv@6.12.6 --legacy-peer-deps
25          CI=false npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
          cname: digitaldawndevelop.xyz
